version: '3.8'

services:
  database:
    image: "postgres:10.16"
    environment:
    - POSTGRES_USER=unicorn_user
    - POSTGRES_PASSWORD=magical_password
    - POSTGRES_DB=rainbow_database
    volumes:
    - database-data:/var/lib/postgresql/data/
    ports:
    - "5432:5432"

  app:
    # environment:
    #   - NODE_ENV=in_docker_compose
    depends_on:
      - database
    build: ./backend
    ports:
      - "3030:3030"
    command: npm start
    # network_mode: host
  
  # elasticsearch browser
  dejavu:
      image: appbaseio/dejavu:3.6.0
      container_name: dejavu
      ports:
          - '1358:1358'
      links:
          - opensearch

  # search engine
  opensearch:
    image: opensearchproject/opensearch:1.2.4
    container_name: opensearch
    environment:
        - plugins.security.disabled=true
        - discovery.type=single-node
        - http.port=9200
        - http.cors.enabled=true
        - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358
        - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
        - http.cors.allow-credentials=true
        - bootstrap.memory_lock=true
        - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
        - '9200:9200'
        - '9300:9300'
    ulimits:
        memlock:
            soft: -1
            hard: -1
    volumes:
        - ./data:/usr/share/opensearch/data

volumes:
  database-data: