
openapi: 3.0.0
info:
  description: MADI Observations MVP API
  version: "0.1"
  title: MADI Observations MVP API
  contact:
    email: james.a.villarrubia@nasa.gov
security:
  - bearerAuth: []

paths:
  $ref#keys: "./keys.yml#paths"
  $ref#obsv: "./observations.yml#paths"
  $ref#auth: "./authentication.yml#paths"

components:
  examples:
    $ref#keys: "./keys.yml#components/examples"
    $ref#obsv: "./observations.yml#components/examples"
    $ref#auth: "./authentication.yml#components/examples"

  schemas:
    int_id:
      type: integer
      readOnly: true
      minimum: 0
      maximum: 100000000
    string_id:
      type: string
      minLength: 4
      maxLength: 36
    iso_date:
      type: string
      format: date-time
      example: '2017-07-21T17:32:28.000Z'
    rpc_string:
      type: string
    $ref#keys: "./keys.yml#components/schemas"
    $ref#obsv: "./observations.yml#components/schemas"
    $ref#erro: "./errors.yml#components/schemas"
    $ref#auth: "./authentication.yml#components/schemas"

